services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: viktorbauer/library-counter:v0.0.1 
    environment:
      - PORT=3003 
      - REDIS_URL=redis://storage
    depends_on:
      - storage
    command: ['npm', 'run', 'start']
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on: 
      - mongo  
  library:
    image: viktorbauer/library:v1.0.1
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - COUNTER_URL=http://counter:3003
      - UrlDb=mongodb://root:example@mongo:27017
    depends_on: 
      - counter
      - mongo-express
    command: ['npm', 'run', 'start']